# -*- coding: utf-8 -*-
"""NLP_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FoWyPEld7bQSFIVzduK8H8F7tZIBDg6i
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

df = pd.read_csv("Dataset-SA.csv")

"""## **Inspect the Dataset**"""

#first five rows
df.head()

#Check the dataset size
df.shape

#checking the columns
df.columns

#Check the sentiment classes


df['Sentiment'].value_counts()

#Check missing values
df.isnull().sum()

#Check the data types
df.info()

#checking some of the reviews
df[['Review', 'Sentiment']].head(10)

"""### **Data Inspection – Insight**
* The dataset contains 205,052 records and 6 attributes.
* The important NLP columns are Review (text input) and Sentiment (target).
* The dataset has 3 sentiment classes: Positive, Negative, and Neutral.
* Positive reviews dominate the dataset with 166,581 records, while Negative has 28,232 and Neutral has 10,239.
* Review has 24,664 missing values, while Summary has only 11 missing values.
* Other columns (product_name, product_price, Rate, Sentiment) have no missing values.
* Therefore, the dataset is imbalanced, and missing review texts will need to be handled before NLP processing.
"""

# Check rows where the Review text is missing
df[df['Review'].isnull()][['Review', 'Summary', 'Sentiment']].head(10)

"""## **Handling the missing values**"""

# Fill missing Review values using the Summary
df['Review'] = df['Review'].fillna(df['Summary'])

# Check remaining missing values in Review
df['Review'].isnull().sum()

# Check the remaining missing Review values
df[df['Review'].isnull()][['Review', 'Summary', 'Sentiment']]

# Remove rows with no review text
df = df.dropna(subset=['Review'])

# Check remaining missing Review values
df['Review'].isnull().sum()

"""## **Check duplicate reviews**"""

# Check for duplicate rows
df.duplicated().sum()

# Remove duplicate rows-duplicate records can affect the model's learning and evaluation.
df = df.drop_duplicates()

# Check the dataset size after removing duplicates
df.shape

"""We started with 205,052 rows and now have 170,675 unique records after handling missing reviews and duplicates.

So the dataset is now cleaner and ready for the next inspection stage.

## **Check sentiment distribution again**
"""

# Check sentiment distribution after cleaning
df['Sentiment'].value_counts()

# Check the length of each review
df['Review'].str.len().describe()

# Display some sample reviews with their sentiment
df[['Review', 'Sentiment']].sample(10, random_state=42)

"""## **Text Preprocessing**

### **cleaning the Review text**
"""

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['Clean_Review'] = df['Review'].apply(clean_text)

df[['Review', 'Clean_Review', 'Sentiment']].head(10)

"""###  **Stopword Removal**

Stopwords are common words such as "the", "is", "and", and "to" that generally
carry limited information for sentiment classification. Removing these words
helps reduce unnecessary text and allows the model to focus on more meaningful
words.
"""

# Download the English stopword list
nltk.download('stopwords')

# Create a set of English stopwords for faster lookup
stop_words = set(stopwords.words('english'))

# Remove stopwords from the cleaned reviews
df['Clean_Review'] = df['Clean_Review'].apply(
    lambda text: ' '.join(
        word for word in text.split()
        if word not in stop_words
    )
)

# Display the original review, processed review, and sentiment
df[['Review', 'Clean_Review', 'Sentiment']].head(10)

"""### **Stemming**

Stemming reduces words to their root form by removing common word endings.
This helps group similar words and reduce the number of unique terms.
"""

# Initialize the Porter Stemmer
stemmer = PorterStemmer()

# Apply stemming to each word in the processed review
df['Stemmed_Review'] = df['Clean_Review'].apply(
    lambda text: ' '.join(stemmer.stem(word) for word in text.split())
)

# Display the original, cleaned, and stemmed reviews
df[['Review', 'Clean_Review', 'Stemmed_Review', 'Sentiment']].head(10)

"""## **Feature Extraction – TF-IDF**

TF-IDF converts text into numerical features based on word importance.
"""

# Create the TF-IDF vectorizer
tfidf = TfidfVectorizer()

# Convert stemmed reviews into numerical features
X = tfidf.fit_transform(df['Stemmed_Review'])

# Store the sentiment labels
y = df['Sentiment']

print("TF-IDF matrix shape:", X.shape)

"""## **Train-Test Split**

The dataset is divided into training and testing sets to evaluate the model on unseen data.
"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""## **Classification Model – Logistic Regression**

Logistic Regression is used to classify reviews into positive, negative, and neutral sentiments.
"""

# Create the Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train, y_train)

print("Model training completed.")

"""## **Prediction**

The trained model is used to predict the sentiments of the test reviews.
"""

# Predict sentiments for the test data
y_pred = model.predict(X_test)

# Display the first 10 predictions
print(y_pred[:10])

"""## **Model Evaluation**

Now in the next step the model is evaluated using accuracy, precision, recall, F1-score, and a confusion matrix.
"""

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1-Score :", round(f1, 4))

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

"""## **Confusion Matrix Visualization**

The confusion matrix is visualized to clearly compare the actual and predicted sentiment classes. It helps identify which sentiments are classified correctly and where the model makes errors.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Define the sentiment class labels
labels = ['negative', 'neutral', 'positive']

# Plot the confusion matrix
plt.figure(figsize=(6, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel('Predicted Sentiment')
plt.ylabel('Actual Sentiment')
plt.title('Confusion Matrix')
plt.show()

"""### **Sample Sentiment Prediction**

Now the trained model is tested on a few new product reviews.
"""

# Sample reviews for testing
sample_reviews = [
    "This product is excellent and worth the money",
    "Very bad product, completely disappointed",
    "It is okay, nothing special"
]

# Apply the same preprocessing used during training
clean_samples = [
    ' '.join(stemmer.stem(word) for word in clean_text(review).split()
             if word not in stop_words)
    for review in sample_reviews
]

# Convert the samples into TF-IDF features
sample_features = tfidf.transform(clean_samples)

# Predict the sentiment
sample_predictions = model.predict(sample_features)

# Display the predictions
for review, sentiment in zip(sample_reviews, sample_predictions):
    print(f"Review: {review}")
    print(f"Predicted Sentiment: {sentiment}\n")

"""## **Sample Prediction Analysis**

The model correctly classified the clearly positive and negative sample
reviews. However, the neutral review, "It is okay, nothing special", was
classified as positive.

This shows that the model has difficulty distinguishing neutral reviews
from positive reviews. This is a limitation of the current sentiment
classification model and may be influenced by the similarity between
neutral and positive language.

## **Working NLP Application Interface**

A simple user interface is created to allow users to enter a Flipkart product review and receive a predicted sentiment. The trained TF-IDF and Logistic Regression model is used to classify the review as Positive, Negative, or Neutral.
"""

# Install Gradio for the user interface
!pip install -q gradio

# Create the sentiment prediction function and interface

import gradio as gr

def predict_sentiment(review):
    # Clean the user's review
    cleaned_review = clean_text(review)

    # Convert the review into TF-IDF features
    review_tfidf = tfidf.transform([cleaned_review])

    # Predict sentiment
    prediction = model.predict(review_tfidf)[0]

    return prediction.upper()


interface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(
        lines=5,
        placeholder="Enter a Flipkart product review here..."
    ),
    outputs=gr.Textbox(label="Predicted Sentiment"),
    title="Flipkart Review Sentiment Analyzer",
    description="Enter a product review to predict whether it is Positive, Negative, or Neutral."
)

interface.launch()